@baseUrl = https://soure-pa.nobe-treino.com.br/saude

# @name authenticate
POST https://soure-pa.nobe-treino.com.br/saude/api/users/authenticate
Content-Type: application/json
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0

{
    "login": "manoelluz",
    "password": "123456"
}
